Support different LLMs besides OpenAI via Langchain
ScrapeGraphAI/Scrapontologies pull request #28
Opened 2024-10-12 09:18 UTC by finger-bone

This PR addresses the issue #26 .

This PR made the `LLMClient` an abstract class, and renamed the original `LLMClient` to `OpenAILLMClient`, with no code change, then implemented LcLLMClient as Langchain LLM Client, which takes any Langchain ChatModel and adapts it into the code. In addition, `BaseParser` had `get_api_key` call from `LLMClient` removed. This call was not used in the old code.

`extract_entities_from_pdf_with_langchain_client.py` is added for testing. The only difference from the `extract_entities_from_pdf.py` is that the new script uses LcLLMClient.

2024-10-13 10:12 UTC, VinciGit00 requested changes

2024-10-13 10:12 UTC, VinciGit00 commented on pyproject.toml
Hi, I do not see any langchain import here, please can you add it?

2024-10-13 10:12 UTC, VinciGit00 commented on scrapontology/llm_client/openai_llm_client.py
Please instead of using requests can you use chatOpenai? (https://python.langchain.com/docs/integrations/chat/openai/) 
Take a look on Scrapegraphai how models are iniated.
You should take a look on these examples from scrapegraphai: https://github.com/ScrapeGraphAI/Scrapegraph-ai/blob/main/scrapegraphai/graphs/abstract_graph.py

2024-10-13 10:12 UTC, VinciGit00 commented on examples/extract_entities_json_schema_from_pdf.py
I would like an initialization of the examples like this please https://github.com/ScrapeGraphAI/Scrapegraph-ai/blob/main/examples/openai/smart_scraper_openai.py

2024-10-13 10:12 UTC, VinciGit00 commented on examples/extract_entities_json_schema_from_pdf.py
(for all the examples)

2024-10-13 11:49 UTC, finger-bone commented on scrapontology/llm_client/openai_llm_client.py
So, if I'm getting it right, you'd prefer using a configuration dictionary (or equivalent) to initialize an LLMClient based on langchain, is that correct? If so, I'll just make corresponding changes.

In addition, if we were to implement a more general LLMClient that supports major langchain chat llms, then there will be no need to implement a more restricted class that only supports openai client, since you siad that you don't want the current requests-version and prefer langchain.

2024-10-13 12:59 UTC, VinciGit00 commented on scrapontology/llm_client/openai_llm_client.py
yes I would like to have something like that and te initialization is done under the hood by the library.
From our experience is easier in this way and more fault tollerant

2024-10-13 13:05 UTC, finger-bone commented on scrapontology/llm_client/openai_llm_client.py
get it, the new commit has addressed that, check if this is how you wanted.

2024-10-13 13:13 UTC, VinciGit00 commented on scrapontology/llm_client.py
Hi @finger-bone I think is almost perfect! You are in the rigth way.

I think the best solution should be integrate init_chat_model from langchain. Here's the documentationhttps://js.langchain.com/docs/how_to/chat_models_universal_init/.

In this way we can skip the vast amount of llm_models initialization  and is more update-tolerant.

Thank you for the effort you are putting for this library.

If you want please write me an email (mvincig11@gmail.com)

2024-10-13 13:24 UTC, finger-bone commented on scrapontology/llm_client.py
sry i didn't know this feature before, thanks for the hints! Have done that.

2024-10-13 14:59 UTC, VinciGit00 commented on scrapontology/llm_client.py
@finger-bone one more thing.
Please can you update all the dependencies inside pyproject.toml with >= instead of ==?
Thank you again

2024-10-13 15:50 UTC, finger-bone commented on scrapontology/llm_client.py
sure thing

2024-10-14 16:49 UTC, lurenss commented
Hi @finger-bone, thank you very much, for your work.

One small thing is needed before merging.

Could you add support for ollama?

Thank you in advance

2024-10-15 00:16 UTC, finger-bone commented
> Could you add support for ollama, always using langchain?

I suppose it already does? Just missing a depenedency, i've added that. 
<img width="1099" alt="image" src="https://github.com/user-attachments/assets/51803018-0ac5-4e5e-b84f-5aa158bef6c9">

2024-10-15 07:19 UTC, VinciGit00 approved these changes
OK thank you

2024-10-15 07:19 UTC, VinciGit00 commented on pyproject.toml
can you add also the support for ollama? After this is finished

2024-10-15 08:24 UTC, lurenss commented
lgtm

2024-10-15 08:24 UTC, merged